apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    run: react-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: react-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: react-app
    spec:
      containers:
      - name: react-app
        image: nheidloff/react-app:latest
        ports:
        - containerPort: 80
        - containerPort: 443      